<?php $page ="For solicitor - Our products";
include("meta_tags.php"); 
include("header.php"); ?>
		<section class="page-title p_relative pt_30 " style="background-color: #fff;">
            <div class="auto-container">
                <div class="content-box">
                    <h1 class="d_block fs_30 lh_40 fw_medium">Our solution</h1>
                    <ul class="bread-crumb p_relative d_block clearfix">
                        <li class="p_relative d_iblock fs_16 lh_22 blue-color pr_15 mr_5">
                            <a href="<?php echo @$weburl;?>" class="blue-color hov-color">Home</a>
                        </li>
                        <li class="p_relative d_iblock fs_16 lh_22 blue-color">For solicitors</li>
                    </ul>
                    <hr>
                </div>
            </div>
        </section>
		    <section class="event-details p_relative pb_40">
            <div class="auto-container">
                <div class="lower-content p_relative d_block">
                    <div class="row clearfix">
                        <div class="col-lg-8 col-md-9 col-sm-12 content-column">
                            <div class="content-box shadow pr_20 pl_20 pt_30 pb_30">
                            	  <h3 class="fs_20 fw_medium mb_20">We provide the following services to Solicitors:</h3>
                            	  <ul class="list clearfix mb_20">
                                    <li class="p_relative d_block fs_16 lh_22 fw_normal pl_20 mb_10"><b>Pagination:</b> Pagination is the practice of organizing the pages of legal documents, such as contracts, court documents, and legal briefs. It is an essential part of legal document preparation, as it helps to ensure that pages are not lost or misplaced and that the documents are presented in an organised and professional manner. Pagination can help to prevent errors, and inconsistencies in legal documents, which can be costly and time-consuming.<br><br>
                                    If you would like to utilise our pagination services, please contact <a href="mailto:pagination@sfrmedical.com">pagination@sfrmedical.com</a>.
                                    </li>
                                    <li class="p_relative d_block fs_16 lh_22 fw_normal pl_20 mb_10"><b>Save time and resources:</b> Expert Witness report for Personal Injury Claims: Expert Witness reports are medico-legal reports generated by expert witnesses offering their opinions on points of controversy in a legal case. A doctor or other medical professional testifies about and gives opinions on medical subjects and issues that have been raised in the particular court case.<br><br>
                                        If you need an Expert Witness, please contact <a href="mailto:expert.witness@sfrmedical.com">expert.witness@sfrmedical.com</a>.
                                    </li>
                                </ul>
                                <div class="table-responsive">
                                    <table class="table table-bordered text-left ">
                                      <thead>
                                        <tr>
                                          <th width="50%" class="pricing-header text-left">Personal Injury Claim/ Service Type</th>
                                          <th width="50%" class="pricing-header text-left">What is it?</th>
                                        </tr>
                                      </thead>
                                      <tbody>
                                        <tr>
                                          <td class="pricing-col1">Accidents at work </td>
                                          <td class="pricing-col1">Slips, Trips and Falls, hit by falling object, crashes &amp; collisions, repetitive strain injury, cuts &amp; lacerations, struck by workers, electrocution.</td>
                                        </tr>
                                        <tr>
                                          <td class="pricing-col1">Road Traffic Claims – MedCO and non-MedCo </td>
                                          <td class="pricing-col1">Non-fatal accidents: Neck strains due to vehicle collision, Spinal injury, head injury, shoulder injury, bone fracture joint dislocation, torn ligament or tendon etc.</td>
                                        </tr>
                                        <tr>
                                          <td class="pricing-col1">Serious Accidents </td>
                                          <td class="pricing-col1">Multiple bone fractures, injury to important organs like the brain, heart, lungs, liver, kidney.</td>
                                        </tr>
                                        <tr>
                                          <td class="pricing-col1">Sports Injury </td>
                                          <td class="pricing-col1">Sprains &amp; strains, swollen muscles, bone fractures, Achilles tendon injuries, rotator cuff injuries, dislocations, stress fracture.</td>
                                        </tr>
                                        <tr>
                                          <td class="pricing-col1">Slips Trips and falls </td>
                                          <td class="pricing-col1">Spinal injury, head injury, bone fracture, bruises on the body</td>
                                        </tr>
                                        <!-- <tr>
                                          <td class="pricing-col1">Injury Claims</td>
                                          <td class="pricing-col1"></td>
                                        </tr> -->
                                        <tr>
                                          <td class="pricing-col1">Criminal Injury </td>
                                          <td class="pricing-col1">Stabbing, Gunshots injury, Hand fight injuries, being hit with a hard object</td>
                                        </tr>
                                        <tr>
                                          <td class="pricing-col1">Employer’s liability </td>
                                          <td class="pricing-col1">For all accidents at work</td>
                                        </tr>
                                        <tr>
                                          <td class="pricing-col1">Public liability </td>
                                          <td class="pricing-col1">Accidents in public spaces – slip &amp; falls, injury in public parks, playgrounds, recreational areas. Injury caused by faulty equipment in the public area. Dog bites or animal attacks.</td>
                                        </tr>
                                        <tr>
                                          <td class="pricing-col1">Industrial diseases </td>
                                          <td class="pricing-col1">Lung diseases, Skin related diseases, Burn related issues, Acid related issues</td>
                                        </tr>
                                      </tbody>
                                    </table>
                                </div>
                                <div class="link mt_20">
                                    <div class="page-inner clearfix">
                                        <div class="left-column pull-left blue-color fs_18 lh_22 fw_bold">
                                            <i class="fa fa-chevron-left fs_14"></i>&nbsp;&nbsp;<a href="<?php echo @$weburl;?>for-solicitor-our-solution">Our Solution</a>
                                        </div>
                                        <div class="right-column pull-right blue-color fs_18 lh_22 fw_bold">
                                            <a href="<?php echo @$weburl;?>for-solicitor-our-purpose"> Our Purpose </a>&nbsp;&nbsp;<i class="fa fa-chevron-right fs_14"></i>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <?php include("sidebar.php"); ?>
                        
                    </div>
                </div>
            </div>
        </section>

<?php include("footer.php"); ?>