<?php $page = "For solicitor - Our products";
include('meta_tags.php');
include('header.php');?>

        <div id="site-content" class="site-content">

            <div class="content-header content-header-inline wrap">
                <div class="content-header-inner wrap ">
                    <!--<h2>WHO WE ARE</h2>-->
                    <h2 class="main-headig">Our products</h2>
                    <div class="breadcrumbs">
                        <div class="breadcrumbs-inner">
                            <!-- Breadcrumb NavXT 6.2.1 -->
                            <span property="itemListElement" typeof="ListItem">
                                <span property="name">For solicitors</span><meta property="position" content="1" />
                            </span>
                            <span property="itemListElement" typeof="ListItem">
                                <span property="name">Our products</span><meta property="position" content="2" />
                            </span>
                        </div>
                    </div>
                </div>
            </div>

            <div id="content-body" class="content-body">
                <div class="content-body-inner wrap">
                    <div class="vc_separator wpb_content_element vc_separator_align_center vc_sep_width_100 vc_sep_pos_align_center vc_separator_no_text vc_custom_1510028822927  vc_custom_1510028822927">
                        <span class="vc_sep_holder vc_sep_holder_l"><span class="vc_sep_line"></span></span>
                        <span class="vc_sep_holder vc_sep_holder_r"><span class="vc_sep_line"></span></span>
                    </div>
                    <!-- The main content -->
                    <main id="main-content" class="main-content" itemprop="mainContentOfPage">
                        <div class="main-content-inner">
                            <div class="content text-content shadow content-padding">
                                <h4>We provide the following services to Solicitors:</h4>
                                <ul>
                                    <li><b>Pagination:</b> Pagination is the practice of organizing the pages of legal documents, such as contracts, court documents, and legal briefs. It is an essential part of legal document preparation, as it helps to ensure that pages are not lost or misplaced and that the documents are presented in an organised and professional manner. Pagination can help to prevent errors, and inconsistencies in legal documents, which can be costly and time-consuming. <br><br>If you would like to utilise our pagination services, please contact <a href="mailto:pagination@sfrmedical.com">pagination@sfrmedical.com</a>. <br><br></li>
                                    <li><b>Expert Witness report for Personal Injury Claims:</b> Expert Witness reports are medico-legal reports generated by expert witnesses offering their opinions on points of controversy in a legal case. A doctor or other medical professional testifies about and gives opinions on medical subjects and issues that have been raised in the particular court case. <br><br>If you need an Expert Witness, please contact <a href="mailto:expert.witness@sfrmedical.com">expert.witness@sfrmedical.com</a></li>
                                </ul>
                                <div class="vc_empty_space h-20"><span class="vc_empty_space_inner"></span></div>
                                <div class="table-responsive">
                                    <table class="table table-bordered text-left " >
                                      <thead>
                                        <tr>
                                          <th width="50%" class="pricing-header text-left">Personal Injury Claim/ Service Type</th>
                                          <th width="50%" class="pricing-header text-left">What is it?</th>
                                        </tr>
                                      </thead>
                                      <tbody>
                                        <tr>
                                          <td class="pricing-col1">Accidents at work </td>
                                          <td class="pricing-col1">Slips, Trips and Falls, hit by falling object, crashes & collisions, repetitive strain injury, cuts & lacerations, struck by workers, electrocution.</td>
                                        </tr>
                                        <tr>
                                          <td class="pricing-col1">Road Traffic Claims – MedCO and non-MedCo </td>
                                          <td class="pricing-col1">Non-fatal accidents: Neck strains due to vehicle collision, Spinal injury, head injury, shoulder injury, bone fracture joint dislocation, torn ligament or tendon etc.</td>
                                        </tr>
                                        <tr>
                                          <td class="pricing-col1">Serious Accidents </td>
                                          <td class="pricing-col1">Multiple bone fractures, injury to important organs like the brain, heart, lungs, liver, kidney.</td>
                                        </tr>
                                        <tr>
                                          <td class="pricing-col1">Sports Injury </td>
                                          <td class="pricing-col1">Sprains & strains, swollen muscles, bone fractures, Achilles tendon injuries, rotator cuff injuries, dislocations, stress fracture.</td>
                                        </tr>
                                        <tr>
                                          <td class="pricing-col1">Slips Trips and falls </td>
                                          <td class="pricing-col1">Spinal injury, head injury, bone fracture, bruises on the body</td>
                                        </tr>
                                        <!-- <tr>
                                          <td class="pricing-col1">Injury Claims</td>
                                          <td class="pricing-col1"></td>
                                        </tr> -->
                                        <tr>
                                          <td class="pricing-col1">Criminal Injury </td>
                                          <td class="pricing-col1">Stabbing, Gunshots injury, Hand fight injuries, being hit with a hard object</td>
                                        </tr>
                                        <tr>
                                          <td class="pricing-col1">Employer’s liability </td>
                                          <td class="pricing-col1">For all accidents at work</td>
                                        </tr>
                                        <tr>
                                          <td class="pricing-col1">Public liability </td>
                                          <td class="pricing-col1">Accidents in public spaces – slip & falls, injury in public parks, playgrounds, recreational areas. Injury caused by faulty equipment in the public area. Dog bites or animal attacks.</td>
                                        </tr>
                                        <tr>
                                          <td class="pricing-col1">Industrial diseases </td>
                                          <td class="pricing-col1">Lung diseases, Skin related diseases, Burn related issues, Acid related issues</td>
                                        </tr>
                                      </tbody>
                                    </table>
                                </div>
                                <!--<div class="vc_empty_space h-20"><span class="vc_empty_space_inner"></span></div>-->
                                <!-- <p>Please reach out to <a href="mailto:expert.witness@sfrmedical.com">expert.witness@sfrmedical.com</a></p> -->
                                <div class="vc_row wpb_row vc_inner vc_row-fluid section_next_prev">
                                    <div class="wpb_column vc_column_container vc_col-md-6 vc_col-sm-6">
                                        <div class="vc_column-inner">
                                            <div class="wpb_wrapper text-content text-left">
                                                <div class="vc_empty_space h-10"><span class="vc_empty_space_inner"></span></div>
                                                <a class="next_prev" href="<?php echo $url;?>for-solicitor-our-solution"><i class="fa fa-chevron-left" aria-hidden="true"></i>&nbsp;&nbsp;Our solution</a>
                                                <div class="vc_empty_space h-10"><span class="vc_empty_space_inner"></span></div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="wpb_column vc_column_container vc_col-md-6 vc_col-sm-6">
                                        <div class="vc_column-inner">
                                            <div class="wpb_wrapper text-content text-right" >
                                                <div class="vc_empty_space h-10"><span class="vc_empty_space_inner"></span></div>
                                                <a class="next_prev" href="<?php echo $url;?>for-solicitor-our-purpose">Our purpose&nbsp;&nbsp;<i class="fa fa-chevron-right" aria-hidden="true"></i></a>
                                                <div class="vc_empty_space h-10"><span class="vc_empty_space_inner"></span></div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- /.main-content-inner -->
                    </main>
                    <!-- /.main-content -->
                    <aside class="main-sidebar">
                        <div class="main-sidebar-inner">
                            
                            <?php include('sidebar.php');?>
                            
                        </div>
                    </aside>

                </div>
                <!-- /.content-body-inner -->
            </div>
            <!-- /.content-body -->
        </div>
        <!-- /.site-content -->

<?php include('footer.php');?>